project:
  type: website
  output-dir: docs

website:
  title: "Math 218 - Spring 2023"
  navbar:
    background: primary
    search: false
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - href: assignments.qmd
        text: Assignments
      - icon: github
        href: https://github.com

  
      

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

