---
title: "Math 218: Spring 2023"
---

## Course information

-   Warner 104, TRF 8:40-9:30AM Eastern

-   Professor: Becky Tang (btang\@middlebury.edu)

    -   Office: Warner 214

    -   Office hours: Tuesdays 3-4pm

    -   Schedule 1:1 meetings via [Calendly](https://calendly.com/beckytang/meet-with-becky?month=2023-02)

-   TA: Doug Rosin

    -   Office hours: Thursdays 7-9pm and Thursdays 7:30-9:30pm in Warner 216 (common space)

Visit the [schedule](schedule.qmd) page to see the current course schedule, lecture notes, and due dates.

Visit the [assignments](assignments.qmd) page to see the current list of assignments.

## Materials

*There is no required textbook for this course.*

You should have a fully-charged laptop, tablet with keyboard, or comparable device to every class.

You should also have R and RStudio installed on your machine. If you do not have either, please follow these [instructions](files/R-installation.pdf).

## Syllabus

The course syllabus can be found [here](files/syllabus_S23.pdf). Please note that the once the semester begins, the schedule on the syllabus may not be up-to-date. Refer to the [schedule](schedule.qmd) page to see the current course schedule.
