---
title: "Schedule"
format:
  html:
    css: styles.css
    page-layout: full
---

**Unless otherwise stated, please submit assignments as a PDF to Canvas.**

Note: course schedule is subject to change.

::: important
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| Date     | Description                            | Class materials                                                                                                       | Assignments                                                                                 | Due date         |
+:========:+========================================+=======================================================================================================================+=============================================================================================+==================+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 1                                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 02/14  | Welcome!                               | [Class introduction](slides/slides-00-welcome.qmd), [intro to base R](live-code/live-code-base-R.qmd)                 |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 02/16  | What is statistical learning?          | [What is statistical learning?](slides/slides-01-what-is.qmd)                                                         |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 02/17  | Lab day                                | [More R coding](live-code/live-code-conditions.qmd), [GitHub Desktop installation](slides/slides-00-installation.qmd) | [Lab 01: Roulette](labs/lab-01-roulette.qmd)                                                | 02/23 at 11:59pm |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 2                                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 02/21  | What is statistical learning? (cont.)  | [What is statistical learning?](slides/slides-01-what-is.qmd)                                                         |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 02/23  | Linear regression                      | [Slides: Linear regression](slides/slides-02-linear-regression.qmd)                                                   |                                                                                             |                  |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | [Live code](live-code/live-code-lin-regression.qmd)                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 02/24  | Linear regression (cont.)              |                                                                                                                       | [Lab 02: Moneyball](labs/lab-02-linear-regression.qmd)                                      | 03/02 at 11:59pm |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          | Lab day                                |                                                                                                                       |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 3                                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 02/28  | KNN regression                         | [Slides: KNN regression](slides/slides-03-knn-regression.qmd)                                                         | [KNN pseudocode](files/knn_pseudocode.qmd)                                                  | 03/02 in class   |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 03/02  | KNN regression: implementation         | Live code: [Writing functions](live-code/live-code-functions.qmd)                                                     | [KNN group pseudocode](implementations/implementation_knn_regression_1.qmd) (steps 1-2)     | 03/03 in class   |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 03/03  | KNN: implementation                    |                                                                                                                       | [KNN group implementation](implementations/implementation_knn_regression_1.qmd) (step 3)    | 03/06 11:59pm    |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 4                                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 03/07  | KNN regression (pt. 2)                 | [Slides](slides/slides-04-knn-regression-pt2.qmd)                                                                     | [KNN regression: categorical features](implementations/implementation_knn_regression_2.qmd) | 03/09 11:59pm    |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | Live code: [encoding](live-code/live-code-encoding.qmd)                                                               |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 03/09  | Validation                             | [Slides](slides/slides-05-validation.qmd)                                                                             |                                                                                             |                  |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | Live code: [LOOCV](live-code/live-code-loocv.qmd)                                                                     |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 3/10   | Lab 03: Validation                     | Live code: [lists](live-code/live-code-lists.qmd)                                                                     | [Lab 03: ski resorts](labs/lab-03-cross-validation.qmd)                                     | 03/16 11:59pm    |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 5                                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 03/14  | Regression trees (part 1)              | [Slides](slides/slides-06-regression-trees-01.qmd)                                                                    |                                                                                             |                  |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | Live code: [binary recursive split](live-code/live-code-regression-trees.qmd)                                         |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 03/16  | Regression trees (part 2)              | [Slides](slides/slides-07-regression-trees-02.qmd)                                                                    |                                                                                             |                  |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | Live code: [pruning](live-code/live-code-pruning.qmd)                                                                 |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 03/17  | NO CLASS                               | Work on Lab 04!                                                                                                       | [Lab 04: forest fires](labs/lab-04-regression-trees.qmd)                                    | 03/30 11:59pm    |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | SPRING BREAK                                                                                                          |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 6                                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 03/28  | Introduce midterm                      | [Slides](slides/slides-08-bootstrap.qmd)                                                                              | [Bootstrap implementation](implementations/implementation_bootstrap.qmd)                    | 03/29 11:59pm    |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          | Bootstrap                              |                                                                                                                       |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 03/30  | Project introduction                   | [Project description](project/description.qmd)                                                                        | [Bagging implementation](implementations/implementation_bagging_regression.qmd)             | Ungraded         |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          | Bagging                                | [Slides](slides/slides-09-bag-forests.qmd)                                                                            | [Live code](live-code/live-code-bagging-implementation.qmd) from class                      |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 03/31  | Bagging (cont.) + Random forests       | [Slides](slides/slides-09-bag-forests.qmd)                                                                            | Midterm: computational assignment                                                           | 04/02 11:59pm    |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | Live code: [randomForest](live-code/live-code-bagging.qmd)                                                            |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 7                                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 04/04  | Bayes classifier + Logistic regression | [Slides](slides/slides-10-logistic.qmd)                                                                               | Please e-mail about project partners!                                                       |                  |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | Live code: [fitting logistic regression](live-code/live-code-logistic.qmd)                                            |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 04/06  | Model Assessment + KNN classification  | [Slides](slides/slides-11-confusion-auc.qmd)                                                                          | Please e-mail about project partners!                                                       |                  |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | Live code: [fitting logistic regression](live-code/live-code-logistic.qmd)                                            |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 04/07  | KNN implementation                     |                                                                                                                       | [KNN classification implementation](implementations/implementation_knn_classification.qmd)  | 04/11 11:59pm    |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| Sa 04/08 | Project                                | Last day to pick group                                                                                                |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 8                                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 04/11  | Imbalanced data + Validation           | [Live code](live-code/live-code-class_imbalance.qmd)                                                                  |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 04/13  | Project                                | [Slides](slides/slides-project-01.qmd) + [instructions](project/merge-conflicts.qmd) for merge conflict activity      | [Lab 05: Wagga Wagga rain](labs/lab-05-logistic-knn-class.qmd)                              | 04/20 11:59pm    |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | Project proposal                                                                                                      |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 04/14  | NO CLASS                               | Spring symposium                                                                                                      |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 9                                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 04/18  | Classification trees                   | [Slides](slides/slides-12-classification-trees.qmd)                                                                   |                                                                                             |                  |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | [Worksheet](files/classification-trees-exercise.pdf) building trees                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 04/20  | Classification tree (cont.)            | [Slides](slides/slides-13-classification-trees-2.qmd)                                                                 |                                                                                             |                  |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | [Live code](live-code/live-code-classification-trees.qmd)                                                             |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 04/21  | Implementation                         |                                                                                                                       | [Bagged classification trees](implementations/implementation_bagging_classification.qmd)    | 04/27 11:59pm    |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| Su 04/23 | Project                                |                                                                                                                       | Proposal due                                                                                | Tonight 11:59pm  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 10                                                                                                               |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 04/25  | Project                                |                                                                                                                       | [Project](project/description.qmd) plan                                                     | 04/30 at 11:59pm |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 04/27  | K-means clustering                     | [Slides](slides/slides-14-k-means.qmd)                                                                                |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 04/28  | K-means clustering (cont.)             | Slides (cont.)                                                                                                        |                                                                                             |                  |
|          |                                        |                                                                                                                       |                                                                                             |                  |
|          |                                        | [Live code](live-code/live-code-kmeans.qmd)                                                                           |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| Su 04/30 |                                        |                                                                                                                       | Plans due                                                                                   | Tonight 11:59pm  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 11                                                                                                               |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 05/02  | Project                                |                                                                                                                       |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 05/04  | Hierarchical clustering                | [Slides](slides/slides-15-h-clust.qmd)                                                                                | K-means [implementation](implementations/implementation_kmeans.qmd)                         | 05/15 11:59pm    |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 05/05  | Clustering (cont.)                     |                                                                                                                       |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| Su 05/07 | Project                                |                                                                                                                       | Draft due!                                                                                  | 11:59pm          |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
|          |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | WEEK 12                                                                                                               |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| T 05/09  | Project                                | Peer review for drafts                                                                                                |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| R 05/11  | Project                                |                                                                                                                       | Report + Repo + Slides                                                                      | Tonight 11:59pm  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
| F 05/12  |                                        | ::: important                                                                                                         |                                                                                             |                  |
|          |                                        | Project presentations!                                                                                                |                                                                                             |                  |
|          |                                        | :::                                                                                                                   |                                                                                             |                  |
+----------+----------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+------------------+
:::
